### ISSUE TITLE
Questions about subset partitioning strategy in PCTSP

### ISSUE THREAD

**Issue by hyh3512** [henry-yeh/GLOP#4]
Hello, I have some questions about the subset partitioning strategy when reading your paper and analyzing the relevant code. In the `Sampler` class in the code, when we divide the number of subsets into a large number, I see a lot of repeated nodes between subsets. In addition, when calculating the penalty, you seem to calculate it based on the global nodes that are not visited in a single subset, which confuses me. According to my understanding, this method seems to be contrary to the traditional idea of ​​subset partitioning, because usually we want the subsets to process some nodes independently, rather than trying to cover all global nodes.

**Comment by henry-yeh** [comment]
Hi there, thanks for your interest!

Could you please clarify which lines of code you are referring to?

**Comment by hyh3512** [comment]
In the Sample file, line 40
```python 
visit_mask, depot_mask = self.update_mask(visit_mask, depot_mask, cur_node, collected_prize)
'''
In this line of code, the updates of visit_mask and depot_mask do not seem to effectively prevent node duplication between subsets. When the total number of nodes is 500 and the number of subsets is 50, the subsets contain the same nodes.
line 57
'''
return (torch.eq(expanded_nodes, expanded_sol)==0).all(dim=1)
'''
and '''gen_penalty(self, solutions, node_penalty) '''function(line 59)
The penalty calculated by the gen_penalty function is based on the global node uncovered situation, rather than the independence of each subset.
In the train.py file, the calculation in line 32(''' objs = eval(subsets, coor, sol_penalty, opts)''') seems to be an independent calculation for each subset. According to your penalty calculation logic, it should be expected that each subset contains all nodes. This confuses me. Thank you very much for your help.

**Comment by henry-yeh** [comment]
The code generates subsets for **PCTSP** (GLOP-S). In PCTSP, each subset is an independently sampled subsetting solution, i.e. the to-visit nodes.
